version: '3.7'

services:
  app:
    image: openjdk:8-jre-alpine 
    build:
      context: .
      dockerfile: dockerfile 
    ports:
      - "8080:8080" 
    depends_on:
      - db 
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/prueba 
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prueba
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql